add a skeleton for the FSM, the basic architecture.
ultimateownsz/PySeas pull request #89
Opened 2024-12-31 14:40 UTC by PurpleProg

# Finite State Machine

## Summary

This PR add the base of the Finite State Machine
It's just a draft, so we can discuss how to implement that essential feature, which need to be scalable and clear (i mean understandable, readable). This is an exemple of how we could use classes as states.

## Related Issues
related to #83, the state manager

## ✅ Checklist:

  - [x] 🛠️ I have tested my code, and it works as expected (e.g., game runs without errors).
  - [x] 📝 I have made sure that the code follows the project's formatting and style guidelines.
  - [x] 💬 Code is commented (if applicable)

2024-12-31 14:49 UTC, PurpleProg commented
Also, i think the codebase is somewhat messy, maybe we could remove CLI and rename GUI to game or something generic like that. There is so much stuff everywhere for such a few lines of codes (1000 line of python out of 3500 lines of random markdown and stuff). A general structure clean up could be usefull. For exemple font and images could be inside data.
And the current GUI class (could become the state manager) is currently a dataclass, but dataclasses are, well, for data, for instances that are ment to be compared to each other, like items but not a main game loop. idk it just feel weird to have a dataclass here, a normal class would look cleaner and more readable to me.

I am sorry if that looks... picky ? annoying ? I'm trying to be constructive but it's not easy lol. And that's just my opinion, i might be totally wrong.

2024-12-31 15:32 UTC, ultimateownsz commented
> Also, i think the codebase is somewhat messy, maybe we could remove CLI and rename GUI to game or something generic like that. There is so much stuff everywhere for such a few lines of codes (1000 line of python out of 3500 lines of random markdown and stuff). A general structure clean up could be usefull. For exemple font and images could be inside data. And the current GUI class (could become the state manager) is currently a dataclass, but dataclasses are, well, for data, for instances that are ment to be compared to each other, like items but not a main game loop. idk it just feel weird to have a dataclass here, a normal class would look cleaner and more readable to me.

What would be your suggestion to rename it? First it was py_version and pygame so that's why I'm confused. A better structure is a good idea. Data classes look to me more readable, but I think it's more a preference, I think we can refactor it to a normal class, because pygame doesn't support data classes out of the box and could give us more problems later on.

> I am sorry if that looks... picky ? annoying ? I'm trying to be constructive but it's not easy lol. And that's just my opinion, i might be totally wrong.

I value your opinion! This is good constructive feedback!

2024-12-31 15:33 UTC, ultimateownsz commented
> # Finite State Machine
> ## Summary
> 
> This PR add the base of the Finite State Machine It's just a draft, so we can discuss how to implement that essential feature, which need to be scalable and clear (i mean understandable, readable). This is an exemple of how we could use classes as states.
> ## Related Issues
> 
> related to #83, the state manager
> ## ✅ Checklist:
> 
>     * [x]  🛠️ I have tested my code, and it works as expected (e.g., game runs without errors).
> 
>     * [x]  📝 I have made sure that the code follows the project's formatting and style guidelines.
> 
>     * [x]  💬 Code is commented (if applicable)

Hmm yes I was first thinking of a simple enum state machine class, and later work on other iterations. Perhaps it's best to see what works best, and try out different results!

2024-12-31 17:17 UTC, PurpleProg commented
a combination of the two seem good, as we might encapsulate the game logic (like player turns and all) inside the gamerunning state, and use something like that.

2025-01-02 09:58 UTC, ultimateownsz commented
> a combination of the two seem good, as we might encapsulate the game logic (like player turns and all) inside the gamerunning state, and use something like that.

Do you want to work on this or do you suggest we work together on different solutions?

2025-01-02 10:47 UTC, ultimateownsz commented on src/states/game_running.py
Will this class handle just the game states or run the whole game?

2025-01-03 23:16 UTC, PurpleProg commented on src/states/game_running.py
that one is just the state of the game during gameplay, so not the whole game, the whole game would be ran by the currently named GUI class.

2025-01-03 23:17 UTC, PurpleProg commented
> > a combination of the two seem good, as we might encapsulate the game logic (like player turns and all) inside the gamerunning state, and use something like that.
> 
> Do you want to work on this or do you suggest we work together on different solutions?

I would like to work on that yes, but if you wanna try something else let me know.

2025-01-03 23:51 UTC, ultimateownsz commented
You have my permission to work on that, you have permissions to assign yourself to that task in github projects! @PurpleProg

2025-01-05 16:53 UTC, PurpleProg commented
that way of handling states is pretty much working rn, what do you think about it ? It should make it easyer to add a state, as you can make your own file, the only time you have to change other's work is when you want to add a way of switching to your new state. And as it use a stack, it's cool because it remember the last ones, when you exit a states it's nice and easy to go back to the last one. What do you think about it ?

2025-01-05 21:23 UTC, ultimateownsz requested changes
I think deleting CLI code just to make the codebase more clear is not the best approach, we could use some code of it perhaps in the pygame code to a certain degree or perhaps work later on the CLI game if it's needed.

Overall your PR looks good, I would still add enums to the code to make it more clear which state you are adding as (new) contributor.

2025-01-05 21:28 UTC, PurpleProg commented
> Overall your PR looks good, I would still add enums to the code to make it more clear which state you are adding as (new) contributor.

i don't understand how enums would help here. Could you explain that a bit more pls ?

2025-01-05 21:33 UTC, ultimateownsz commented
- Using enums could allow us to clearly define all possible states in one place. This helps others understand the available states at a glance.
- Since enums provide a fixed set of values, they reduce the likelihood of typos or invalid state transitions.
- State transitions in the FSM become easier to read and debug because the states have meaningful names.
- As the game grows, enums make it straightforward to add new states without affecting other parts of the code significantly.

For example:

```py
from enum import Enum

class GameState(Enum):
    MENU = 1
    PLAYING = 2
    PAUSED = 3
    GAME_OVER = 4
```

Do you think this could help? Or do you think this could make it harder?

2025-01-05 21:48 UTC, PurpleProg commented
enums are a fixed set of constants. But the current game states are not constants. So what we could do is to set them as integer and just check which state is currently selected, but, we would lose the advantages of using a stack. And i think that would not add anything more that classes, as we can use the `state.__class__.__name__` to access the name of the class, so i don't think using enums would be better that classes.

2025-01-05 21:59 UTC, ultimateownsz commented
Hmm, I think your approach sounds better, do what you think works best. I don't have much experience with using it, need to see it in action I suppose.

2025-01-05 22:02 UTC, PurpleProg commented
> Hmm, I think your approach sounds better, do what you think works best. I don't have much experience with using it, need to see it in action I suppose.

you can try do write your own state, for example a simple "paused" state with just a simple transparent overlay. And bind buttons to enter and exit your "pause" (the pause state name is already taken but you get the idea)

2025-01-07 08:49 UTC, ultimateownsz commented
Do you need a review on this PR again?

2025-01-07 21:39 UTC, PurpleProg commented
in fact i just didn't add any debug features, I will add a few tomorow.

2025-01-08 23:02 UTC, ultimateownsz requested changes
Since this PR introduces significant changes to how we add new features to the codebase. I've provided some suggestions for improvements. Your doc strings were well written, but had a few minor grammar issues. Additionally, I made a few code revision suggestions, particularly in the `GameStateManager`. These are not mandatory but could enhance readability and maintainability.

2025-01-09 15:02 UTC, PurpleProg commented on src/gameloop.py
> +    def __str__(self) -> str:
that oneliner isn't really readable, and implementing `duration` should be done (if actually needed) in a PR for delta time and Framerate independence.

2025-01-09 15:05 UTC, PurpleProg commented on src/gameloop.py
> +    def __str__(self) -> str:
and `__str__` is for a quick and easily readable name, `__repr__` would be more appropriate for a more detailed representation of the state.

2025-01-09 15:30 UTC, ultimateownsz commented on src/gameloop.py
> +    def __str__(self) -> str:
Okay yes I agree with you on this. If it isn't used then we can always later decide to have it! If not, that's okay too!

2025-01-09 17:24 UTC, ultimateownsz approved these changes
These changes are approved! Thank you for your time!

2025-01-09 20:51 UTC, merged